### PR TITLE
feat: Make domains selected through interconnect open in target without prompting

### PR DESCRIPTION
**Pull request by zacharee**
Adds a new field to `PreferredApp` called `setByInterconnect`. When true, the bottom sheet won't show an app picker, even if other apps match the Intent.

### CODE REVIEW

**Comment by 1fexd** [comment]
I just tried to test the current behavior and it appears it doesn't work for some reason? MastodonRedirect shows "Open LinkSheet" but just opens LinkSheet without showing the dialog?

**Comment by zacharee** [comment]
You might need to build from the latest commit.

**Comment by zacharee** [comment]
Actually, I think I found the underlying issue here. When selecting apps through LinkSheet, it saves the component as the first Activity in the app, not necessarily the component that actually has the domain filter. So when `BottomSheetGrouper` checks `isLastChosenPosition()` it'll be false in some cases (with Fediverse Redirect, `lastChosen` will be MainActivity, but the resolved component will be RedirectActivity).

I made a new PR for that which should work instead of this one: https://github.com/1fexd/LinkSheet/pull/183

**Comment by 1fexd** [comment]
Okay, will check it out. Do you have Discord or something like that? That would make collaboration at lot easier, especially since we are both committing to the InterConnect library repository.

**Comment by zacharee** [comment]
I sent a friend request.

**Pull request closed without merging**
