### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by Daviteusz**
Translations update from [Daviteusz's Weblate](https://translate.daviteusz.eu) for [LinkSheet/Translate](https://translate.daviteusz.eu/projects/linksheet/translate/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by 1fexd** [comment]
Hey, thanks a lot for the contribution! Would you mind if I create an official Weblate project and we migrate your translations there?

**Comment by Daviteusz** [comment]
Unfortunately, I can't host weblate without outages on my rpi4 with 4 GB of RAM. I have a lot of other services that I need to turn off before I can start translating 😂

But maybe nift4 could host
(https://translate.nift4.org/)
His server has been running flawlessly for many months.

**Comment by 1fexd** [comment]
Haha no what I meant was that I am going to look into these online translation services and set up one up for the project.

**Comment by Daviteusz** [comment]
I misunderstood haha
Of course, you can migrate my translate where you want :)

**Pull request merged**
